CC = gcc
CFLAGS = -c -O2 -g
LIBS = -lm

OBJS = bands.o celt.o cwrs.o entcode.o entdec.o entenc.o kiss_fft.o \
	kiss_fftr.o laplace.o mdct.o modes.o pitch.o \
	quant_bands.o rangedec.o rangeenc.o rate.o testcelt.o vq.o plc.o

.c.o:
	$(CC) $(CFLAGS) $<

testcelt: $(OBJS)
	$(CC) -o $@ $(OBJS) $(LIBS)

clean:
	rm -f testcelt *.o
