LPCNET_HEAD = \
silk/dred_coding.h \
silk/dred_config.h \
silk/dred_decoder.h \
silk/dred_encoder.h \
dnn/dred_rdovae.h \
dnn/lpcnet.h \
dnn/burg.h \
dnn/common.h \
dnn/freq.h \
dnn/fwgan.h \
dnn/fwgan_data.h \
dnn/kiss99.h \
dnn/lpcnet_private.h \
dnn/nnet_data.h \
dnn/nnet.h \
dnn/plc_data.h \
dnn/tansig_table.h \
dnn/vec.h \
dnn/vec_avx.h \
dnn/vec_neon.h \
dnn/dred_rdovae_constants.h \
dnn/dred_rdovae_enc.h \
dnn/dred_rdovae_enc_data.h \
dnn/dred_rdovae_dec.h \
dnn/dred_rdovae_dec_data.h \
dnn/dred_rdovae_stats_data.h \
dnn/neural_pitch.h \
dnn/neural_pitch_data.h
