function(print_configuration)
    message("")
    message("Build configuration:")
    message("")
    message("Build type:\t\t\t\t\t${CMAKE_BUILD_TYPE}")
    message("Architecture:\t\t\t\t\t${ARCH}")
    message("")
    message("Build shared libraries:\t\t\t\t${ENABLE_SHARED}")
    message("Build static libraries:\t\t\t\t${ENABLE_STATIC}")
    message("")
    message("Using C99 variabile-size arrays:\t\t${ENABLE_C99_ARRAYS}")
    message("Compile without the floating point API:\t\t${ENABLE_C99_ARRAYS}")
    message("Enable fast approximations for floating point:\t${ENABLE_C99_ARRAYS}")
    message("Enable non-Opus modes:\t\t\t\t${ENABLE_C99_ARRAYS}")
    if (ENABLE_ASM)
        set(LOG_ASM "TRUE -")
        if (ENABLE_ASM_SSE)
            set(LOG_ASM "${LOG_ASM} sse")
        endif ()
        if (ENABLE_ASM_SSE2)
            set(LOG_ASM "${LOG_ASM} sse2")
        endif ()
        if (ENABLE_ASM_SSE41)
            set(LOG_ASM "${LOG_ASM} sse4.1")
        endif ()
        if (ENABLE_ASM_AVX)
            set(LOG_ASM "${LOG_ASM} axv")
        endif ()
        if (ENABLE_ASM_neon)
            set(LOG_ASM "${LOG_ASM} neon")
        endif ()
    else ()
        set(LOG_ASM "FALSE")
    endif ()
    message("Enable assembly optimizations:\t\t\t${LOG_ASM}")
    message("Enable run-time CPU capabilities detection:\t${ENABLE_RTCD}")
    message("Enable intrinsics optimizations:\t\t${ENABLE_INTRINSICS}")
    message("Enable additional software error checking:\t${ENABLE_ASSERTIONS}")
    message("Enable encoder to make random decisions:\t${ENABLE_FUZZING}")
    message("Enable experimental ambisonic:\t\t\t${ENABLE_EXPERIMENTAL_AMBISONICS}")
    message("")
    message("Build API documentation:\t\t\t${ENABLE_DOC}")
    message("Build extra programs:\t\t\t\t${ENABLE_EXTRA_PROGRAMS}")
    message("")
endfunction()
