SILK_HEAD = \
silk/debug.h \
silk/control.h \
silk/errors.h \
silk/API.h \
silk/typedef.h \
silk/define.h \
silk/main.h \
silk/PLC.h \
silk/structs.h \
silk/tables.h \
silk/tuning_parameters.h \
silk/Inlines.h \
silk/MacroCount.h \
silk/MacroDebug.h \
silk/macros.h \
silk/pitch_est_defines.h \
silk/resampler_private.h \
silk/resampler_rom.h \
silk/resampler_structs.h \
silk/SigProc_FIX.h \
silk/arm/macros_armv4.h \
silk/arm/macros_armv5e.h \
silk/arm/SigProc_FIX_armv4.h \
silk/arm/SigProc_FIX_armv5e.h \
silk/fixed/main_FIX.h \
silk/fixed/structs_FIX.h \
silk/float/main_FLP.h \
silk/float/structs_FLP.h \
silk/float/SigProc_FLP.h
