#ifndef OSCE_CONFIG
#define OSCE_CONFIG


#define OSCE_FEATURES_MAX_HISTORY 350
#define OSCE_FEATURE_DIM (93+64)
#define OSCE_MAX_FEATURE_FRAMES 4

#define OSCE_CLEAN_SPEC_NUM_BANDS 64
#define OSCE_NOISY_SPEC_NUM_BANDS 18

#define OSCE_NO_PITCH_VALUE 7

#define OSCE_PREEMPH 0.85f

#define OSCE_PITCH_HANGOVER 8

#define OSCE_CLEAN_SPEC_START 0
#define OSCE_CLEAN_SPEC_LENGTH 64

#define OSCE_NOISY_CEPSTRUM_START 64
#define OSCE_NOISY_CEPSTRUM_LENGTH 18

#define OSCE_ACORR_START 82
#define OSCE_ACORR_LENGTH 5

#define OSCE_LTP_START 87
#define OSCE_LTP_LENGTH 5

#define OSCE_LOG_GAIN_START 92
#define OSCE_LOG_GAIN_LENGTH 1

#define OSCE_EMBED_PITCH_START 93
#define OSCE_EMBED_PITCH_LENGTH 64

#endif