/***********************************************************************
Copyright (c) 2006-2010, Skype Limited. All rights reserved. 
Redistribution and use in source and binary forms, with or without 
modification, (subject to the limitations in the disclaimer below) 
are permitted provided that the following conditions are met:
- Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above copyright 
notice, this list of conditions and the following disclaimer in the 
documentation and/or other materials provided with the distribution.
- Neither the name of Skype Limited, nor the names of specific 
contributors, may be used to endorse or promote products derived from 
this software without specific prior written permission.
NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED 
BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND 
CONTRIBUTORS ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND 
FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF 
USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON 
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
***********************************************************************/

/**********************************************/
/* This file has been automatically generated */
/*                                            */
/* ROM usage:  0.22 + 0.90 kB                 */
/**********************************************/

#include "SKP_Silk_structs.h"
#include "SKP_Silk_tables.h"
#include "SKP_Silk_tables_NLSF_CB1_10.h"

const SKP_uint16 SKP_Silk_NLSF_MSVQ_CB1_10_CDF[ NLSF_MSVQ_CB1_10_VECTORS + NLSF_MSVQ_CB1_10_STAGES ] =
{
            0,
        21247,
        28440,
        34489,
        38585,
        41021,
        43353,
        45401,
        47050,
        48562,
        49890,
        51162,
        52379,
        53597,
        54536,
        55435,
        56260,
        57049,
        57805,
        58562,
        59286,
        59979,
        60588,
        61122,
        61613,
        62103,
        62593,
        63084,
        63574,
        64064,
        64554,
        65045,
        65535,
            0,
        34067,
        42961,
        48025,
        52103,
        55532,
        58961,
        62391,
        65535,
            0,
        30146,
        40804,
        46615,
        50906,
        55016,
        58624,
        62080,
        65535,
            0,
        31530,
        38758,
        44096,
        48990,
        53478,
        57776,
        62074,
        65535,
            0,
        14400,
        25503,
        35253,
        44194,
        52756,
        58308,
        62234,
        65535,
            0,
        26248,
        35939,
        44449,
        49733,
        53988,
        58062,
        61799,
        65535,
            0,
        20097,
        31540,
        38344,
        44584,
        50823,
        56798,
        62277,
        65535
};

const SKP_uint16 * const SKP_Silk_NLSF_MSVQ_CB1_10_CDF_start_ptr[ NLSF_MSVQ_CB1_10_STAGES ] =
{
     &SKP_Silk_NLSF_MSVQ_CB1_10_CDF[   0 ],
     &SKP_Silk_NLSF_MSVQ_CB1_10_CDF[  33 ],
     &SKP_Silk_NLSF_MSVQ_CB1_10_CDF[  42 ],
     &SKP_Silk_NLSF_MSVQ_CB1_10_CDF[  51 ],
     &SKP_Silk_NLSF_MSVQ_CB1_10_CDF[  60 ],
     &SKP_Silk_NLSF_MSVQ_CB1_10_CDF[  69 ],
     &SKP_Silk_NLSF_MSVQ_CB1_10_CDF[  78 ]
};

const SKP_int SKP_Silk_NLSF_MSVQ_CB1_10_CDF_middle_idx[ NLSF_MSVQ_CB1_10_STAGES ] =
{
       4,
       2,
       2,
       2,
       4,
       3,
       3
};

const SKP_uint8 SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q4[ NLSF_MSVQ_CB1_10_VECTORS ] =
{
               26,               51,
               55,               64,
               76,               77,
               80,               85,
               87,               90,
               91,               92,
               92,               98,
               99,              101,
              102,              103,
              103,              104,
              105,              108,
              111,              113,
              113,              113,
              113,              113,
              113,              113,
              113,              113,
               15,               46,
               59,               64,
               68,               68,
               68,               70,
               18,               42,
               56,               63,
               64,               67,
               68,               68,
               17,               51,
               58,               60,
               62,               63,
               63,               68,
               35,               41,
               44,               46,
               47,               57,
               65,               69,
               21,               44,
               47,               58,
               63,               64,
               66,               66,
               27,               40,
               52,               54,
               54,               55,
               57,               69
};

const SKP_int SKP_Silk_NLSF_MSVQ_CB1_10_ndelta_min_Q15[ 10 + 1 ] =
{
              293,
               32,
              225,
              280,
              153,
               23,
               13,
               14,
                9,
                3,
              688
};

const SKP_int8 SKP_Silk_NLSF_MSVQ_CB1_10_Q8[ 10 * NLSF_MSVQ_CB1_10_VECTORS ] =
{
             -113,              -92,
              -68,              -43,
              -20,                3,
               28,               52,
               78,              100,
             -114,             -101,
              -75,              -53,
              -30,               -7,
               20,               45,
               72,               96,
              -98,              -81,
              -58,              -33,
              -10,               10,
               35,               58,
               82,              103,
             -110,              -99,
              -80,              -61,
              -38,              -15,
               12,               38,
               66,               89,
             -115,             -108,
              -77,              -49,
              -21,                4,
               29,               53,
               79,              102,
             -101,              -81,
              -55,              -29,
               -7,               23,
               47,               71,
               93,              110,
             -100,              -83,
              -65,              -44,
              -25,               -7,
               19,               45,
               72,               96,
             -110,             -100,
              -85,              -45,
              -25,               -8,
               22,               39,
               78,               97,
             -115,             -107,
              -89,              -69,
              -36,               -9,
               20,               45,
               72,               99,
             -113,              -99,
              -69,              -38,
              -12,               16,
               44,               68,
               92,              109,
             -109,              -98,
              -84,              -60,
              -19,               -3,
               18,               43,
               61,               98,
              -99,              -77,
              -46,              -17,
               10,               35,
               55,               74,
               92,              106,
             -105,              -91,
              -70,              -42,
               -1,               17,
               35,               58,
               75,               99,
              -90,              -77,
              -53,              -38,
              -21,                0,
               28,               49,
               76,               97,
             -110,             -101,
              -80,              -29,
               -8,                6,
               30,               48,
               82,               99,
             -110,              -92,
              -55,              -19,
                4,               25,
               43,               62,
               84,              101,
             -101,              -88,
              -73,              -58,
              -45,              -26,
               21,               46,
               71,               98,
              -83,              -67,
              -40,              -22,
               -2,               19,
               41,               63,
               85,              103,
             -112,             -103,
              -89,              -62,
               -8,               15,
               33,               56,
               74,               97,
             -117,              -73,
              -56,              -33,
              -13,               11,
               34,               57,
               80,              101,
             -110,             -100,
              -84,              -72,
              -59,              -15,
               21,               45,
               76,               96,
             -103,              -90,
              -72,              -59,
              -40,                1,
               32,               56,
               82,               98,
             -107,              -97,
              -79,              -54,
              -37,              -21,
               -4,               22,
               71,               94,
              -97,              -67,
              -27,               -2,
               29,               44,
               58,               71,
               82,               98,
              -89,              -74,
              -55,              -45,
              -30,              -18,
               -2,               23,
               65,               97,
             -106,              -82,
              -56,              -31,
               -5,               34,
               59,               65,
               68,               78,
             -107,              -82,
              -57,              -31,
               20,               31,
               34,               35,
               68,              103,
             -109,              -83,
              -56,              -32,
               -6,               18,
               49,               82,
              109,              116,
             -103,              -82,
              -50,              -17,
               -6,                2,
               19,               56,
               83,              105,
             -106,              -82,
              -54,              -30,
               -1,               32,
               41,               49,
               52,               98,
              -98,              -66,
              -36,                0,
                5,               12,
               14,               26,
               64,               97,
             -105,              -80,
              -53,              -29,
                2,               30,
               76,               90,
               94,               96,
               -2,               -2,
               -2,                0,
               -1,               -1,
               -1,                0,
                0,                0,
                2,                2,
                3,                4,
                3,                5,
                7,                6,
                4,                2,
                8,                9,
                5,               -2,
                1,                1,
                1,                0,
               -2,               -2,
                1,                1,
                2,               -2,
               -7,              -11,
              -11,                0,
               -1,                0,
                1,                0,
               -3,               -2,
               -6,               -3,
                2,               -4,
               10,                5,
               -1,               -3,
               -5,               -7,
               11,                7,
                4,               -1,
                1,                1,
                0,                1,
                7,               10,
                3,               -1,
               -6,               -2,
               -3,               -4,
                0,               -1,
               -2,               -2,
                0,                3,
                0,               -5,
              -11,              -10,
               -1,                1,
                1,                1,
                1,                1,
                1,                1,
                1,                0,
                2,                1,
               -2,               -4,
               -5,               -3,
               -3,               -3,
               -3,               -3,
                3,                2,
                3,                5,
                4,                0,
               -3,               -9,
               -5,               -1,
                3,                2,
                2,               -1,
               -1,               -1,
               -2,                6,
                7,                6,
               -2,               -5,
               -9,               -4,
               -1,               -3,
               -3,                1,
                2,                2,
               -6,               -9,
                6,                3,
                3,                1,
                2,                1,
               -1,               -1,
                3,                1,
               -2,                2,
                4,               -3,
                9,                3,
               -3,                4,
                1,                0,
               -1,               -4,
               -6,               11,
                4,                1,
                2,               -1,
               -1,               -1,
               -1,               -2,
                0,                0,
                0,                0,
               -1,                0,
                6,                3,
                1,                0,
                1,                1,
                1,               -1,
                1,                2,
               -5,                6,
                3,                2,
                3,                4,
                2,                1,
                0,                1,
                0,               -1,
               -2,                2,
                1,               -1,
               -6,               -8,
                2,               -1,
                0,               -1,
                8,                1,
               -5,                0,
               -1,               -1,
                0,                0,
                0,                0,
               -2,                0,
               -2,               -8,
                3,                0,
                2,                2,
                1,                1,
                0,                0,
                1,                0,
               -2,               10,
                1,               -4,
               -1,               -4,
               -6,                6,
                3,                4,
                4,                1,
               -1,               -2,
                0,                1,
                2,                1,
                1,                4,
                1,                1,
               -1,               -2,
                0,                4,
                2,                0,
               -1,               -2,
               -1,               -2,
                1,                0,
               -1,               -2,
               -2,                1,
               -1,               -4,
                0,               -1,
               -1,               -4,
                0,               -1,
               -2,               -4,
               -1,                0,
                3,                3,
                1,                1,
               -1,               -3,
                1,                1,
                1,                1,
               -1,               -2,
                4,                3,
                2,                0,
               -1,               -2,
                5,               -1,
               -3,                0,
               -1,                0,
                0,               -1,
                0,                0,
                0,               -2,
                0,               -1,
               -7,                6,
                2,                0,
               -2,                4,
               -4,                1,
               -1,                1,
                1,                0,
                1,               -1,
                1,                2,
                2,                0,
                1,                1,
                0,                1,
               -1,                1,
                1,               -4,
                2,               -1,
                0,               -1,
               -1,               -1,
                0,               -1,
               -3,               -1,
               -2,                1,
                1,               -3,
               -1,                1,
                1,                1,
               -2,                1,
                0,                1,
               -5,                1,
               -2,                1,
                1,                1,
               -2,                0,
                0,                1,
               -1,                0,
                5,               -3,
                0,               -3,
                2,                0,
               -3,               -2,
               -2,                0,
                0,               -1,
                2,                2,
                1,                0,
               -4,               -1,
                2,                1,
               -1,               -3,
               -5,                1,
                1,                2,
               -2,                0,
                1,                1,
                2,                2,
                1,                1,
                0,               -1,
               -2,               -1,
                0,                0,
                0,                2,
                0,                0,
                1,               -1,
                0,                3,
               -2,               -1,
                1,                0,
                0,                0,
                1,                0,
                0,                0,
                4,               -1,
                1,               -3,
                0,                1,
                1,                4,
                0,               -1,
               -1,                0,
               -1,               -1,
               -2,               -3,
               -1,                0,
               -1,                0,
                0,                1,
               -3,                0,
               -1,                2,
               -4,                0,
                1,                1,
                1,                1,
                0,                0,
               -2,               -1,
                0,                0,
                3,               -2,
               -1,                1,
                1,                1,
                4,               -1,
               -1,                0,
                1,                0,
                0,                0,
                0,               -1
};

const SKP_Silk_NLSF_CBS SKP_Silk_NLSF_CB1_10_Stage_info[ NLSF_MSVQ_CB1_10_STAGES ] =
{
        {  32, &SKP_Silk_NLSF_MSVQ_CB1_10_Q8[ 10 *   0 ], &SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q4[   0 ] },
        {   8, &SKP_Silk_NLSF_MSVQ_CB1_10_Q8[ 10 *  32 ], &SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q4[  32 ] },
        {   8, &SKP_Silk_NLSF_MSVQ_CB1_10_Q8[ 10 *  40 ], &SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q4[  40 ] },
        {   8, &SKP_Silk_NLSF_MSVQ_CB1_10_Q8[ 10 *  48 ], &SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q4[  48 ] },
        {   8, &SKP_Silk_NLSF_MSVQ_CB1_10_Q8[ 10 *  56 ], &SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q4[  56 ] },
        {   8, &SKP_Silk_NLSF_MSVQ_CB1_10_Q8[ 10 *  64 ], &SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q4[  64 ] },
        {   8, &SKP_Silk_NLSF_MSVQ_CB1_10_Q8[ 10 *  72 ], &SKP_Silk_NLSF_MSVQ_CB1_10_rates_Q4[  72 ] }
};

const SKP_Silk_NLSF_CB_struct SKP_Silk_NLSF_CB1_10 =
{
        NLSF_MSVQ_CB1_10_STAGES,
        SKP_Silk_NLSF_CB1_10_Stage_info,
        SKP_Silk_NLSF_MSVQ_CB1_10_ndelta_min_Q15,
        SKP_Silk_NLSF_MSVQ_CB1_10_CDF,
        SKP_Silk_NLSF_MSVQ_CB1_10_CDF_start_ptr,
        SKP_Silk_NLSF_MSVQ_CB1_10_CDF_middle_idx
};

