name: Makefile

on: [push, pull_request]

permissions: read-all

jobs:

 MakefileBuild:
    name: Makefile/${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Linux/GCC",
            os: ubuntu-latest,
            compiler: gcc,
          }
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Build
        run: make -f Makefile.unix -j 2
      - name: Test
        run: make -f Makefile.unix check -j 2
      - name: Clean
        run: make -f Makefile.unix clean
