name: Repository

on: [push, pull_request]

permissions: read-all

jobs:
  CheckTrailingWhiteSpaces:
    name: Check trailing white spaces
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Check Whitespaces
        run: |
          git diff-tree --check origin/main HEAD
